### PR TITLE
testpr: use rattler-build.

### PR DESCRIPTION
**Pull request by oursland**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @wolfv @baszalmstra - some exciting stuff happening here :).

There are some issues in switching from boa to pixi/rattler-build. It seems like the created package for some reason contains the whole environment, and `.git` folder etc. - how do we avoid this? The CI runner is also running out of space super quickly, any idea why?

**Comment by oursland** [comment]
I believe this is because the current uploaded packages are non-existent.  [`linux_64` correctly identifies the packages to be built are already built](https://github.com/RoboStack/ros-jazzy/actions/runs/10874068202/job/30170932516?pr=8#step:9:19) and skips them.  `macos_arm64` finds many packages, but tries to build the others, and the other platforms have no uploaded artifacts.

**Comment by Tobias-Fischer** [comment]
I am happy with the list of package that need to be built, but not happy with the contents of the packages :)

**Comment by traversaro** [comment]
> There are some issues in switching from boa to pixi/rattler-build. It seems like the created package for some reason contains the whole environment, and `.git` folder etc. - how do we avoid this? The CI runner is also running out of space super quickly, any idea why?

I experienced this as well! The issue is https://github.com/prefix-dev/rattler-build/issues/981 . Quoting @wolfv :

> You can easily work around this by building outside the recipe folder or by setting a different output directory explicitly.

**Comment by traversaro** [comment]
I attempted a fix in https://github.com/RoboStack/ros-jazzy/pull/8#issuecomment-2351793781, not sure if it works.

**Comment by Tobias-Fischer** [comment]
@wolfv - I might be blind but where do I  see which package is being built? I wonder if it still builds in the correct order or ignores dependencies.

**Comment by wolfv** [comment]
@Tobias-Fischer I see some builds in osx-64. They _should_ be in the right order ... :)

**Comment by Tobias-Fischer** [comment]
Is it possible to see the order; and/or see the package that is being built currently @wolfv?

**Comment by wolfv** [comment]
It prints these things in the right order. I think one problem is that we should associate the source with each output. Otherwise each output will refetch _all_ sources again. I thought I had already changed that in vinca but apparently not. The other option would be to generate the multiple recipes and use the `--recipe-dir` option.

Screenshot 2024-09-21 at 15 00 37
Screenshot 2024-09-21 at 15 00 12

**Comment by oursland** [comment]
I prefer the multiple recipes option for `testpr`, but believe that any issues preventing proper operation of the single, large recipe also be fixed.

I'll make the changes to this PR for multiple recipes.

**Comment by wolfv** [comment]
I think the issue was that we skipped recipe generation for packages already on `robostack-jazzy` but didn't include the channel when building with rattler-build. Let's see if it's fixed now!

**Pull request closed without merging**
